import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import RangeSlider from 'react-range-slider-input'
import 'react-range-slider-input/dist/style.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lotus Mood Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <RangeSlider 
          id='range-slider'
          rangeSlideDisabled={true}
          thumbsDisabled={[true,false]}
          defaultValue={[0,50]}
        />
      </main>
    </>
  )
}
